const datas = [
  {
    id: "1",
    name: "John Doe",
    age: 28,
    location: "New York",
    language: "English",
    role: "user",
  },
  {
    id: "2",
    name: "Alice Smith",
    age: 24,
    location: "Los Angeles",
    language: "English",
    role: "user",
  },
  {
    id: "3",
    name: "Mohammed Khan",
    age: 32,
    location: "Dubai",
    language: "Arabic",
    role: "admin",
  },
  {
    id: "4",
    name: "Sophie Martin",
    age: 29,
    location: "Paris",
    language: "French",
    role: "user",
  },
  {
    id: "5",
    name: "Luis Rodriguez",
    age: 26,
    location: "Madrid",
    language: "Spanish",
    role: "admin",
  },
  {
    id: "6",
    name: "Marta Gómez",
    age: 31,
    location: "Barcelona",
    language: "Spanish",
    role: "user",
  },
  {
    id: "7",
    name: "Yuki Tanaka",
    age: 27,
    location: "Tokyo",
    language: "Japanese",
    role: "user",
  },
  {
    id: "8",
    name: "Elena Petrova",
    age: 35,
    location: "Moscow",
    language: "Russian",
    role: "admin",
  },
  {
    id: "9",
    name: "Sebastian Müller",
    age: 23,
    location: "Berlin",
    language: "German",
    role: "user",
  },
  {
    id: "10",
    name: "Isabella Rossi",
    age: 30,
    location: "Rome",
    language: "Italian",
    role: "user",
  },
];

module.exports = datas;
